### ISSUE TITLE
After update to 1.3.7/1.3.8, "Plugin unavailable" error message

### ISSUE THREAD

**Issue by zyzzyxdonta** [grafana/opcua-datasource#100]
Hi!

After updating to 1.3.7, the server address is now editable again. However, we now receive a "Plugin unavailable" error message.

Might this be due to a broken gpx_opcua_linux_amd64? If I run this executable it fails with the following error message:

```
# /var/lib/grafana/plugins/grafana-opcua-datasource/gpx_opcua_linux_amd64 
The application to execute does not exist: '/var/lib/grafana/plugins/grafana-opcua-datasource/gpx_opcua_linux_amd64.dll'.
```

We use Grafana 9.2.0.

Thanks in advance.

cc: @zenker

**Comment by zyzzyxdonta** [comment]
The same problem still occurs with 1.3.8.

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
