### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by na-am** [grafana/opcua-datasource#35]
I just installed the plugin, but my grafana 7.5.10 says: grafana-opcua-datasource - Missing signature

how can i use the datasource regardless to this message?

**Comment by Sarrybro** [comment]
Hi I am using 8.2.1 and the plugin is still unsigned there too, however, its working! so my question is sort of any update on when or how this will be signed? and does really matter if it is not?

**Comment by alydersen** [comment]
Thanks to @srclosson for fixing this now with version 1.1.4!
