### ISSUE TITLE
Enhancement: Read streaming values and report using grafana live

### ISSUE THREAD

**Issue by srclosson** [grafana/opcua-datasource#52]
This enhancement is for reading and reporting streaming values without having to refresh values. These are now supported using grafana live.

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won't receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
