### ISSUE TITLE
OPC UA Client - TimeStamp Handling (server time or source time) for Historic Data Raw Read

### ISSUE THREAD

**Issue by ukalt** [grafana/opcua-datasource#57]
Hello @srclosson 

found one issue regarding the TimeStamp Handling for Historic Data Raw Read.
It looks like that the plugin queries historic raw data including "Server Time" and not "Source Time".
In my case our used OPC UA Server only responds to historic (HA) raw data read if the client uses "Source Time".

This leads to an error "BadTimeStampNotSupported" at the Grafana Query:

The client requested history using a timestamp format the server does not support.
 (i.e requested ServerTimestamp when server only supports SourceTimestamp).

![BadTimeStampNotSupported](https://user-images.githubusercontent.com/103489755/162911698-4a65a1a6-91b3-4b1e-bf06-397bc855cd60.JPG)

In other OPC UA Clients this could be changed by config, example "Ua Expert":

![HA_Read_working_Ua_Expert](https://user-images.githubusercontent.com/103489755/162913298-2bac2898-7740-4905-8bc6-67c3674e0945.JPG)

So my question, is it possible to quickfix this behaviour by config or do you have to rebuild the plugin ?

**Comment by srclosson** [comment]
Hi @ukalt, I've started looking into supporting this. I don't see an issue in getting this implemented. Will let you know when I have an idea when the work can be scheduled.

**Comment by ukalt** [comment]
Hi @srclosson, sounds great. Thx for the feedback.

**Comment by ukalt** [comment]
Planned Release Date ?

Stephanie Closson ***@***.***> schrieb am Fr., 6. Mai 2022,
18:52:
