### ISSUE TITLE
Support using variables

### ISSUE THREAD

**Issue by harvidsen** [grafana/opcua-datasource#58]
It seems like it's not possible to use [variables](https://grafana.com/docs/grafana/latest/variables/) as a part of the **Instance** input. This would be a great feature as it would allow for more possibilities with template panels. If I try to input

```
${my-top-node-variable}.SOME.RDS.CODE
```

in the Instance field, the field becomes empty when i press enter. It seems like the input string does not evaluate. Is this something that can be supported?

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won't receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
