### ISSUE TITLE
Browse from currently selected node

### ISSUE THREAD

**Issue by harvidsen** [grafana/opcua-datasource#62]
Hello! We are using this plugin more and more, so I though I'd submit some "nice to have" UI enhancements.

I often miss the left arrow when expanding subnodes and select a node that does not contain any value. Then it would be nice if, when a node is already selected, the browsing started from the currently selected node. As you can see here

![Screenshot from 2022-05-31 13-39-53](https://user-images.githubusercontent.com/62279738/171165934-a281b8cc-951f-48f0-ad49-cc5c56f0d034.png)

when I have selected a node and click the magnifying glass, the browsing starts at the top nodes again and I have to navigate down to where I was again.

**Comment by srclosson** [comment]
I'd actually like to modify the query editor entirely...

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won't receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
