### ISSUE TITLE
Release for Grafana v9.0.2 linux-arm

### ISSUE THREAD

**Issue by BitWhatElse** [grafana/opcua-datasource#67]
Is it planned to release the plugin for Grafana V9 on linux-arm? I would have an exciting use-case with a Kunbus RevPi device.
(actually grafana-opcua-datasource v is not supported on your system (Grafana v9.0.2 linux-arm))

Thanks a lot!

**Comment by drom89** [comment]
I want to install Grafana with this plugin on my Raspberry Pi too 😥

**Comment by appienvanveen** [comment]
I'm interested in this too. 

@srclosson How difficult would it be do this by ourself? Can you give some global guidelines how to do this?

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
