### ISSUE TITLE
Build for Grafana-arm64

### ISSUE THREAD

**Issue by NeViNez** [grafana/opcua-datasource#71]
Machine: MacOs arm64 (m1 pro)

Running the
`grafana-cli plugins install grafana-opcua-datasource`

Returns the error:
`grafana-opcua-datasource v is not supported on your system (Grafana v9.1.6 darwin-arm64)`

Is ever OPC UA build would be available on Darwin-arm64 through Grafana repos?

By the way, how to build it on local machine for local Grafana instance?

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
