### ISSUE TITLE
Support nodes with string type identifier

### ISSUE THREAD

**Issue by EletroLaix** [grafana/opcua-datasource#72]
Greetings,
during the first tests with your plug-in I realized that inserting a node with string type identifier the module gives me an error.

### Step 1
![image](https://user-images.githubusercontent.com/20475076/201160164-81e77939-1a63-44f4-89e8-68f25ba16b29.png)
### Step 2
![image](https://user-images.githubusercontent.com/20475076/201161214-c2a78b10-fe8f-45f8-a8df-8dc1ebd7f33d.png)
### Step 3
![image](https://user-images.githubusercontent.com/20475076/201160712-a8b5030c-1ce2-4840-bcf5-b53d2cea9e8a.png)

- Am I doing something wrong?
- Can you confirm that in this version the plug-in does not support nodes with this type of ID?

Thank you in advance for your reply.

## Documentation of the standard
- https://reference.opcfoundation.org/v105/Core/docs/Part6/5.2.2/#5.2.2.9

## Other information
![image](https://user-images.githubusercontent.com/20475076/201161835-ebe563c5-64f2-4320-a00e-70b5341c2c84.png)
![image](https://user-images.githubusercontent.com/20475076/201161996-e0b2251c-1ff6-415e-bc1a-19ee04d52cfa.png)

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
