### ISSUE TITLE
Hangs when click Save & Test : Testing... this could take up to a couple of minutes

### ISSUE THREAD

**Issue by tharindupr** [grafana/opcua-datasource#97]
Following is the screenshot of the issue. 

![image](https://github.com/grafana/opcua-datasource/assets/6535021/cf3b7861-4991-49cd-af8b-dd1b01bde524)

My Grafana version is 10, and OPC UA plugin version is 1.1.6

And my OPC UA server successfully connects to other clients.

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
