### ISSUE TITLE
v1.3.6 not available in grafana plugins

### ISSUE THREAD

**Issue by xmoov** [grafana/opcua-datasource#98]
I can't seem to be able to install v1.3.6 from inside grafana. It says v1.2.2 is the latest version. The URL field doesn't work on v1.2.2 which was fixed in v1.3.6. I really love to use the plugin!

**Comment by itsgareth** [comment]
The OPCUA Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

Thank you for your understanding.
